[versions]
compile-sdk = "36"
min-sdk = "26"

[libraries]

[plugins]
sjy-detekt = { id = "com.sanjaya.buildlogic.detekt" }
sjy-lib = { id = "com.sanjaya.buildlogic.lib" }
sjy-compose = { id = "com.sanjaya.buildlogic.compose" }
sjy-app = { id = "com.sanjaya.buildlogic.app" }
sjy-firebase = { id = "com.sanjaya.buildlogic.firebase" }
